# .air.toml - minimal config for Go web server

# Working directory (project root)
root = "."
tmp_dir = "tmp"

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/main ./cmd"

  # Binary file to run after build
  bin = "tmp/main"

  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Ignore these folders
  exclude_dir = ["assets", "tmp", "vendor"]

  # Delay before restart (ms) - prevents too many restarts
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
